RankStay_Web/RankStay_Web/Controllers/NavController.cs
using Microsoft.AspNetCore.Mvc;

namespace RankStay_Web.Controllers
{
    public class NavController : Controller
    {
        public IActionResult About()
        {
            return PartialView("_Part_About");
        }

        public IActionResult Services()
        {
            return PartialView("_Part_Service");
        }

        public IActionResult Projects()
        {
            return PartialView("_Part_Project");
        }
    }
}

RankStay_Web/RankStay_Web/Views/Shared/_Layout.cshtml
@{
    int UserRole = Convert.ToInt32(Context.Session.GetString("UserRole"));
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>RankStay</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link href="/favicon.ico" rel="icon">

    @*modal
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @*modal*@

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&family=Roboto:wght@500;700&display=swap"
          rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary text-white d-none d-lg-flex">
        <div class="container py-3">
            <div class="d-flex align-items-center">
                <h2>
                    <a asp-action="Index" asp-controller="Home" class="text-white fw-bold m-0">RankStay</a>
                </h2>
                <div class="ms-auto d-flex align-items-center">
                    <small class="ms-4"><i class="fa fa-map-marker-alt me-3"></i>10109 Rohrmoser, San José, CR</small>
                    <small class="ms-4"><i class="fa fa-envelope me-3"></i>info@rankstay.com</small>
                    <small class="ms-4"><i class="fa fa-phone-alt me-3"></i>+506 2231 67890</small>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid bg-white sticky-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg bg-white navbar-light p-lg-0">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand d-lg-none">
                    <h1 class="fw-bold m-0">RankStay</h1>
                </a>
                <button type="button" class="navbar-toggler me-0" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a asp-action="Index" asp-controller="Home" class="nav-item nav-link active">Inicio</a>
                        <a asp-action="About" asp-controller="Nav" class="nav-item nav-link">Nosotros</a>
                        <a asp-action="Services" asp-controller="Nav" class="nav-item nav-link">Servicios</a>
                        <a asp-action="Projects" asp-controller="Nav" class="nav-item nav-link">Proyectos</a>
                        @if (UserRole == 1)
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Admin</a>
                                <div class="dropdown-menu bg-light rounded-0 rounded-bottom m-0">
                                    <a asp-action="Users" asp-controller="User" class="dropdown-item">Usuarios</a>
                                    <a asp-action="Provinces" asp-controller="Province" class="dropdown-item">Provincias</a>
                                    <a asp-action="Reviews" asp-controller="Review" class="dropdown-item">Reseñas</a>
                                </div>
                            </div>
                        }
                    </div>
                    <div class="ms-auto d-none d-lg-block">
                        <a asp-action="Login" asp-controller="Auth" class="btn btn-primary rounded-pill py-2 px-3">Salir</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->

    @RenderBody()

    <!-- Footer Start -->
    <div class="container-fluid bg-dark footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Nuestra oficina</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>10109 Rohrmoser, San José, CR</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+506 2231 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@rankstay.com</p>
                    <div class="d-flex pt-3">
                        <a class="btn btn-square btn-light rounded-circle me-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="btn btn-square btn-light rounded-circle me-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="btn btn-square btn-light rounded-circle me-2" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <a class="btn btn-square btn-light rounded-circle me-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Enlaces rápidos</h4>
                    <a class="btn btn-link" href="">Nosotros</a>
                    <a class="btn btn-link" href="">Contacto</a>
                    <a class="btn btn-link" href="">Servicios</a>
                    <a class="btn btn-link" href="">Términos y condiciones</a>
                    <a class="btn btn-link" href="">Ayuda</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Horarios</h4>
                    <p class="mb-1">Lunes - Viernes</p>
                    <h6 class="text-light">09:00 am - 07:00 pm</h6>
                    <p class="mb-1">Sábado</p>
                    <h6 class="text-light">09:00 am - 12:00 pm</h6>
                    <p class="mb-1">Domingo</p>
                    <h6 class="text-light">Cerrado</h6>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">Boletín</h4>
                    <p>Subscríbete a nuestro boletín de noticias</p>
                    <div class="position-relative w-100">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text"
                               placeholder="Tu correo">
                        <button type="button"
                                class="btn btn-light py-2 position-absolute top-0 end-0 mt-2 me-2">
                            Subscribirse
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Copyright Start -->
    <div class="container-fluid copyright py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="fw-medium text-light" href="#">RankStay</a>, Derechos Reservados.
                </div>
                <div class="col-md-6 text-center text-md-end">
                   ___________
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top">
        <i class="bi bi-arrow-up"></i>
    </a>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/modals.js"></script>

    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script type="text/javascript">
        $(document).ready(function () {
            let table = new DataTable('#Table', {
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json',
                },
            });
        });
    </script>
</body>
</html>

RankStay_Web/RankStay_Web/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/auth.css">
    <link href="/favicon.ico" rel="icon">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</body>
</html>

RankStay_Web/RankStay_Web/Views/Shared/_Part_About.cshtml
<!-- About Start -->
<div class="row container-xxl about my-5">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-6">
                <div class="h-100 d-flex align-items-center justify-content-center" style="min-height: 300px;">
                </div>
            </div>
            <div class="col-lg-6 pt-lg-5 wow fadeIn" data-wow-delay="0.5s">
                <div class="bg-white rounded-top p-5 mt-lg-5">
                    <p class="fs-5 fw-medium text-primary">Sobre nosotros</p>
                    <h1 class="display-6 mb-4">La Mejor Fuente para Escoger tu Próxima Vivienda</h1>
                    <p class="mb-4">
                        En RankStay puedes calificar agregar las residencias en las que has vivido y
                        calificar para ayudar a los demás a facilitar la búsqueda de su próximo hogar.
                    </p>
                    <div class="row g-5 pt-2 mb-5">
                        <div class="col-sm-6">
                            <img class="img-fluid mb-4" src="img/icon/icon-5.png" alt="">
                            <h5 class="mb-3">Información</h5>
                            <span>Podrás ver las diferentes opciones, escoge la que más te convenga</span>
                        </div>
                        <div class="col-sm-6">
                            <img class="img-fluid mb-4" src="img/icon/icon-2.png" alt="">
                            <h5 class="mb-3">Comunidad</h5>
                            <span>Ayuda a los demás a encontrar su hogar ideal</span>
                        </div>
                    </div>
                    <a class="btn btn-primary rounded-pill py-3 px-5" href="">Ver más</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Carousel.cshtml
<!-- Carousel Start -->
<div class="container-fluid px-0 mb-5">
    <div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="w-100" src="img/carousel-1.jpg" alt="Image">
                <div class="carousel-caption">
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="col-lg-7 text-start">
                                <p class="fs-4 text-white animated slideInRight">
                                    Bienvenido a
                                    <strong>RankStay</strong>
                                </p>
                                <h1 class="display-1 text-white mb-4 animated slideInRight">
                                    Comparte tu experiencia en viviendas
                                </h1>
                                <a href=""
                                   class="btn btn-primary rounded-pill py-3 px-5 animated slideInRight">
                                    Explorar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="w-100" src="img/carousel-2.jpg" alt="Image">
                <div class="carousel-caption">
                    <div class="container">
                        <div class="row justify-content-end">
                            <div class="col-lg-7 text-end">
                                <p class="fs-4 text-white animated slideInLeft">
                                    Bienvenido a <strong>RankStay</strong>
                                </p>
                                <h1 class="display-1 text-white mb-5 animated slideInLeft">
                                    Descubre los mejores lugares para vivir
                                </h1>
                                <a href=""
                                   class="btn btn-primary rounded-pill py-3 px-5 animated slideInLeft">
                                    Explorar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#header-carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<!-- Carousel End -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Features.cshtml
<!-- Features Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-0 feature-row">
            <div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.1s">
                <div class="feature-item border h-100 p-5">
                    <div class="btn-square bg-light rounded-circle mb-4" style="width: 64px; height: 64px;">
                        <img class="img-fluid" src="img/icon/icon-1.png" alt="Icon">
                    </div>
                    <h5 class="mb-3">Basado en calificaciones</h5>
                    <p class="mb-0">Escoge tu apartamento baso en las experiencias de los demás</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.3s">
                <div class="feature-item border h-100 p-5">
                    <div class="btn-square bg-light rounded-circle mb-4" style="width: 64px; height: 64px;">
                        <img class="img-fluid" src="img/icon/icon-2.png" alt="Icon">
                    </div>
                    <h5 class="mb-3">A tu gusto</h5>
                    <p class="mb-0">Vive donde tus expectativas se cumplan</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.5s">
                <div class="feature-item border h-100 p-5">
                    <div class="btn-square bg-light rounded-circle mb-4" style="width: 64px; height: 64px;">
                        <img class="img-fluid" src="img/icon/icon-3.png" alt="Icon">
                    </div>
                    <h5 class="mb-3">Precios justos</h5>
                    <p class="mb-0">Elige la vivienda que más se ajuste a tu presupuesto</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.7s">
                <div class="feature-item border h-100 p-5">
                    <div class="btn-square bg-light rounded-circle mb-4" style="width: 64px; height: 64px;">
                        <img class="img-fluid" src="img/icon/icon-4.png" alt="Icon">
                    </div>
                    <h5 class="mb-3">Ayuda 24/7</h5>
                    <p class="mb-0">Contáctanos por nuestros medios en caso de necesitar ayuda</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Features End -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Project.cshtml
<!-- Project Start -->
<div class="container-xxl pt-5">
    <div class="container">
        <div class="text-center text-md-start pb-5 pb-md-0 wow fadeInUp" data-wow-delay="0.1s"
             style="max-width: 500px;">
            <p class="fs-5 fw-medium text-primary">Nuestros proyectos</p>
            <h1 class="display-5 mb-5">Estamos trabajando para crecer</h1>
        </div>
        <div class="owl-carousel project-carousel wow fadeInUp" data-wow-delay="0.1s">
            <div class="project-item mb-5">
                <div class="position-relative">
                    <img class="img-fluid" src="img/project-1.jpg" alt="">
                    <div class="project-overlay">
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="img/project-1.jpg"
                           data-lightbox="project"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="">
                            <i class="fa fa-link"></i>
                        </a>
                    </div>
                </div>
                <div class="p-4">
                    <a class="d-block h5" href="">Análisis de datos</a>
                    <span>Estamos enfocados en crecer en esta área</span>
                </div>
            </div>
            <div class="project-item mb-5">
                <div class="position-relative">
                    <img class="img-fluid" src="img/project-2.jpg" alt="">
                    <div class="project-overlay">
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="img/project-2.jpg"
                           data-lightbox="project"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="">
                            <i class="fa fa-link"></i>
                        </a>
                    </div>
                </div>
                <div class="p-4">
                    <a class="d-block h5" href="">Estrategias de mercadeo</a>
                    <span>Estamos enfocados en crecer en esta área</span>
                </div>
            </div>
            <div class="project-item mb-5">
                <div class="position-relative">
                    <img class="img-fluid" src="img/project-3.jpg" alt="">
                    <div class="project-overlay">
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="img/project-3.jpg"
                           data-lightbox="project"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="">
                            <i class="fa fa-link"></i>
                        </a>
                    </div>
                </div>
                <div class="p-4">
                    <a class="d-block h5" href="">Desarrollo de negocios</a>
                    <span>Estamos enfocados en crecer en esta área</span>
                </div>
            </div>
            <div class="project-item mb-5">
                <div class="position-relative">
                    <img class="img-fluid" src="img/project-4.jpg" alt="">
                    <div class="project-overlay">
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="img/project-4.jpg"
                           data-lightbox="project"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-lg-square btn-light rounded-circle m-1" href="">
                            <i class="fa fa-link"></i>
                        </a>
                    </div>
                </div>
                <div class="p-4">
                    <a class="d-block h5" href="">Redes sociales</a>
                    <span>Estamos enfocados en crecer en esta área</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Project End -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Quote.cshtml
<!-- Quote Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
                <p class="fs-5 fw-medium text-primary">Contacto</p>
                <h1 class="display-5 mb-4">Tienes dudas? Contáctanos!</h1>
                <p>
                    Contamos con diferentes canales por los que puedes hacer llegar tus consultas y nuestro equipo te ayudará con lo que necesites.
                </p>
                <a class="mt-3 d-inline-flex align-items-center rounded overflow-hidden border border-primary" href="">
                    <span class="btn-lg-square bg-primary" style="width: 55px; height: 55px;">
                        <i class="fa fa-phone-alt text-white"></i>
                    </span>
                    <span class="fs-5 fw-medium mx-4">+506 2231 67890</span>
                </a>
            </div>
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
                <h2 class="mb-4">Tu consulta</h2>
                <div class="row g-3">
                    <div class="col-sm-6">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="name" placeholder="Your Name">
                            <label for="name">Tu nombre</label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-floating">
                            <input type="email" class="form-control" id="mail" placeholder="Your Email">
                            <label for="mail">Tu correo</label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="mobile" placeholder="Your Mobile">
                            <label for="mobile">Tu número telefónico</label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-floating">
                            <select class="form-select" id="service">
                                <option selected>Categoría 1</option>
                                <option value="">Categoría 2</option>
                                <option value="">Categoría 3</option>
                                <option value="">Categoría 4</option>
                            </select>
                            <label for="service">Selecciona una categoría</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-floating">
                            <textarea class="form-control" placeholder="Leave a message here" id="message"
                                      style="height: 130px"></textarea>
                            <label for="message">Consulta</label>
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <button class="btn btn-primary w-100 py-3" type="submit">Enviar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Quote Start -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Service.cshtml
<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center mx-auto wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <p class="fs-5 fw-medium text-primary">Únete a nosotros</p>
            <h1 class="display-5 mb-5">Las ventajas de formar parte de RankStay</h1>
        </div>
        <div class="row g-4">
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="service-item position-relative h-100">
                    <div class="service-text rounded p-5">
                        <div class="btn-square bg-light rounded-circle mx-auto mb-4"
                             style="width: 64px; height: 64px;">
                            <img class="img-fluid" src="img/icon/icon-5.png" alt="Icon">
                        </div>
                        <h5 class="mb-3">
                            Opiniones reales
                        </h5>
                        <p class="mb-0">
                            Nos aseguramos que las calificaciones que lees son de personas reales
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                <div class="service-item position-relative h-100">
                    <div class="service-text rounded p-5">
                        <div class="btn-square bg-light rounded-circle mx-auto mb-4"
                             style="width: 64px; height: 64px;">
                            <img class="img-fluid" src="img/icon/icon-6.png" alt="Icon">
                        </div>
                        <h5 class="mb-3">
                            Perspectiva amplia
                        </h5>
                        <p class="mb-0">
                            Podrás ver las diferentes experiencias de las personas y escoger con seguridad
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                <div class="service-item position-relative h-100">
                    <div class="service-text rounded p-5">
                        <div class="btn-square bg-light rounded-circle mx-auto mb-4"
                             style="width: 64px; height: 64px;">
                            <img class="img-fluid" src="img/icon/icon-7.png" alt="Icon">
                        </div>
                        <h5 class="mb-3">
                            Contenido variado
                        </h5>
                        <p class="mb-0">
                            Estamos en constante crecimiento en nuestras redes sociales
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service End -->

RankStay_Web/RankStay_Web/Views/Shared/_Part_Testimonial.cshtml
<!-- Testimonial Start -->
<div class="container-xxl pt-5">
    <div class="container">
        <div class="text-center text-md-start pb-5 pb-md-0 wow fadeInUp" data-wow-delay="0.1s"
             style="max-width: 500px;">
            <p class="fs-5 fw-medium text-primary">Testimonios</p>
            <h1 class="display-5 mb-5">Experiencias de nuestros usuarios!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
            <div class="testimonial-item rounded p-4 p-lg-5 mb-5">
                <img class="mb-4" src="img/testimonial-1.jpg" alt="">
                <p class="mb-4">
                    RankStay me ayudó a encontrar el hogar donde viví los 3 años que duré en el bachillerato. Fácil de usar y una comunidad dispuesta a ayudar
                </p>
                <h5>Nombre Apellido</h5>
                <span class="text-primary">Profesión</span>
            </div>
            <div class="testimonial-item rounded p-4 p-lg-5 mb-5">
                <img class="mb-4" src="img/testimonial-2.jpg" alt="">
                <p class="mb-4">
                    RankStay me ayudó a encontrar el hogar donde viví los 3 años que duré en el bachillerato. Fácil de usar y una comunidad dispuesta a ayudar
                </p>
                <h5>Nombre Apellido</h5>
                <span class="text-primary">Profesión</span>
            </div>
            <div class="testimonial-item rounded p-4 p-lg-5 mb-5">
                <img class="mb-4" src="img/testimonial-3.jpg" alt="">
                <p class="mb-4">
                    RankStay me ayudó a encontrar el hogar donde viví los 3 años que duré en el bachillerato. Fácil de usar y una comunidad dispuesta a ayudar
                </p>
                <h5>Nombre Apellido</h5>
                <span class="text-primary">Profesión</span>
            </div>
            <div class="testimonial-item rounded p-4 p-lg-5 mb-5">
                <img class="mb-4" src="img/testimonial-4.jpg" alt="">
                <p class="mb-4">
                    RankStay me ayudó a encontrar el hogar donde viví los 3 años que duré en el bachillerato. Fácil de usar y una comunidad dispuesta a ayudar
                </p>
                <h5>Nombre Apellido</h5>
                <span class="text-primary">Profesión</span>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->