RankStay_Web/RankStay_Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RankStay_Web.Models;

namespace RankStay_Web.Controllers
{
    public class HomeController : Controller
    {
        readonly ProvinceModel _provinceModel = new();
        readonly PropertyModel _propertyModel = new();

        public async Task<IActionResult> Index()
        {
            return View(await _provinceModel.GetListProvinces());
        }

        [HttpGet("Home/Province/{provinceId}")]
        public async Task<IActionResult> Province(int provinceId)
        {
            return View(await _propertyModel.GetPropertiesByProvince(provinceId));
        }
    }
}

RankStay_Web/RankStay_Web/Controllers/PropertyController.cs
using Microsoft.AspNetCore.Mvc;
using RankStay_Web.Entities;
using RankStay_Web.Models;

namespace RankStay_Web.Controllers
{
    public class PropertyController : Controller
    {
        readonly PropertyModel _propertyModel = new();
        readonly ReviewModel _reviewModel = new();

        //[FilterSessionValidation]
        [HttpGet]
        public IActionResult RegisterProperty()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterProperty(PropertyObj propertyObj)
        {
            return _propertyModel.RegisterProperty(propertyObj) != null
                ? RedirectToAction("Index", "Home") : View();
        }


        [HttpGet("Property/Property/{propertyId}")]
        public async Task<IActionResult> Property(int propertyId)
        {
            return View(await _reviewModel.GetReviewsByProperty(propertyId));
        }
    }
}

RankStay_Web/RankStay_Web/Controllers/ProvinceController.cs
using Microsoft.AspNetCore.Mvc;
using RankStay_Web.Entities;
using RankStay_Web.Models;

namespace RankStay_Web.Controllers
{
    public class ProvinceController : Controller
    {
        readonly ProvinceModel _provinceModel = new();
        

        [HttpGet]
        public async Task<IActionResult> Provinces()
        {
            return View(await _provinceModel.GetListProvinces());
        }
        
        [HttpGet]
        public IActionResult RegisterProvince()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterProvince(ProvinceObj provinceObj)
        {
            return _provinceModel.RegisterProvince(provinceObj) != null 
                ? RedirectToAction("Index", "Home") : View();
        }

        [HttpGet("Province/EditProvince/{provinceId}")]
        public async Task<IActionResult> EditProvince(int provinceId)
        {
            return View(await _provinceModel.GetProvince(provinceId));
        }


        [HttpPost]
        public ActionResult EditProvince(ProvinceObj provinceObj)
        {
            provinceObj.PropertyCount = 2;
            provinceObj.ProvincePhoto = "lorem.pgn";
            return _provinceModel.PutProvince(provinceObj) != null
                ? RedirectToAction("Provinces","Province"): View();
        }
    }
}

RankStay_Web/RankStay_Web/Views/Home/Index.cshtml
@model List<RankStay_Web.Entities.ProvinceObj>

<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" role="status" style="width: 3rem; height: 3rem;"></div>
</div>
<!-- Spinner End -->
@await Html.PartialAsync("_Part_Carousel")
@await Html.PartialAsync("_Part_Features")
<!-- Provinces Start -->
<div class="container">
    <div class="">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-4 mb-4">
                    <a asp-action="Province" asp-controller="Home" asp-route-ID="@item.ProvinceId">
                        <div class="card">
                            <img src="~/img/src/@item.ProvincePhoto" class="card-img-top" alt="Province photo">
                            <div class="card-body">
                                <h5 class="card-title">@item.ProvinceName</h5>
                                <p class="card-text">@item.PropertyCount propiedades</p>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>
<!-- Provinces End -->
@await Html.PartialAsync("_Part_About")
@await Html.PartialAsync("_Part_Service")
@await Html.PartialAsync("_Part_Project")
@await Html.PartialAsync("_Part_Quote")
@await Html.PartialAsync("_Part_Team")
@await Html.PartialAsync("_Part_Testimonial")

RankStay_Web/RankStay_Web/Views/Home/Province.cshtml
@model List<RankStay_Web.Entities.PropertyObj>

@*Hero*@
<div class="hero" style="background: #000 url('/img/src/@Html.DisplayFor(model => model.First().ProvincePhoto)') center center no-repeat; background-size: cover; position: relative;">
    <div class="container">
        <div class="hero-content">
            <div class="row">
                <div class="col-md-12">
                    @if (Model.Any())
                    {
                        <h1>
                            <span class="hero-title">Propiedades registradas en </span>
                            <span class="text-primary">@Html.DisplayFor(model => model.First().ProvinceName)</span>
                        </h1>
                    }
                    else
                    {
                        <h1>No hay propiedades registradas en esta provincia</h1>
                    }
                </div>
                <div class="col-md-6">
                    <p>Selecciona una propiedad para conocer sus calificaciones</p>
                </div>
                @*<div class="col-md-6">
                    <p>Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image Bootstrap Hero Image</p>
                </div>*@
            </div>
        </div>
    </div>
</div>
@*Hero*@

<div class="container-xxl pt-5 mb-5">
    @*<img src="/img/src/@Html.DisplayFor(model => model.First().ProvincePhoto)"/>
    @if (Model.Any())
    {
        <h1>Propiedades registradas en <span class="text-primary">@Html.DisplayFor(model => model.First().ProvinceName)</span></h1>
    }
    else
    {
        <h1>No hay propiedades registradas en esta provincia</h1>
    }
    <p>Selecciona una propiedad para conocer sus calificaciones</p>*@
    <a asp-action="RegisterProperty" asp-controller="Property" class="btn btn-primary rounded-pill py-3 px-5">Agregar propiedad</a>

    <div class="mt-5">
        @foreach (var item in Model)
        {
            <a asp-action="Property" asp-controller="Property" asp-route-ID="@item.PropertyId">
                <div class="card flex-row mb-4">
                    <img class="card-img-left" src="https://holidayhome.stayfritz.com/_published/stayfritz/1047387/274c034d-515b-4a24-a8a0-8d8ecfd1baf4/thumbnail_xs.webp" style="width: 200px; border-radius: 5px 0 0 5px" alt="loft" />
                    <div class="card-body">
                        <h4 class="card-title h5 h4-sm mb-3">@item.PropertyName</h4>
                        <div class="card-text property-reviews mb-2">
                            @if (item.AverageReviewStar.HasValue)
                            {
                                @for (int i = 0; i < 5; i++)
                                {
                                    if (i < (int)item.AverageReviewStar)
                                    {
                                        <span class="fa fa-star"></span>
                                    }
                                    else
                                    {
                                        <span class="bi bi-star"></span>
                                    }
                                }
                                <span>@item.AverageReviewStar / 5</span>
                            }
                            else
                            {
                                <span>Sin reseñas registradas</span>
                            }
                        </div>
                        <p class="card-text">@item.PropertyDescription</p>
                    </div>
                </div>
            </a>
       }
    </div>
</div>